name: NeuroGuia iOS Release

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-ios:
    name: Build e Deploy iOS App Store
    runs-on: macos-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar o Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependências do Flutter
        run: |
          flutter clean
          flutter pub get

      - name: Criar Chaveiro e Gerar Certificado na Nuvem
        env:
          APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
        run: |
          pip3 install codemagic-cli-tools --break-system-packages
          echo "$(python3 -m site --user-base)/bin" >> $GITHUB_PATH
          export PATH="$(python3 -m site --user-base)/bin:$PATH"
          
          keychain initialize
          
          # Buscamos os arquivos vinculando diretamente ao Bundle ID do seu app
          app-store-connect fetch-signing-files com.maoamiga.app.app \
            --issuer-id="$APP_STORE_ISSUER_ID" \
            --key-id="$APP_STORE_KEY_ID" \
            --private-key="$APP_STORE_CONNECT_KEY" \
            --type=IOS_APP_STORE \
            --platform=IOS \
            --create
          
          keychain add-certificates

      - name: Compilar o pacote IPA (Release)
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
        run: |
          flutter build ipa --release \
            --export-options-plist=ios/export_options.plist \
            --api-key-id="$APP_STORE_KEY_ID" \
            --api-issuer="$APP_STORE_ISSUER_ID"

      - name: Enviar o App para o TestFlight
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
        run: |
          xcrun altool --upload-app --type ios \
            -f build/ios/ipa/*.ipa \
            --apiKey "$APP_STORE_KEY_ID" \
            --apiIssuer "$APP_STORE_ISSUER_ID"